[tool.ruff]
# Never enforce `E501`.
extend-select = [
  # Enabled by default
  # pyflakes
  # "F",
  # pycodestyle
  # "E",
  "W",
  # mccabe
  "C90",
  # isort
  "I",
  # pep8-naming
  "N",
  # pydocstyle
  "D",
  # pyupgrade
  "UP",
  # flake8-2020
  "YTT",
  # flake8-annotations
  "ANN",
  # flake8-bandit
  "S",
  # flake8-blind-except
  "BLE",
  # flake8-boolean-trap
  "FBT",
  # flake8-bugbear
  "B",
  # flake8-builtins
  "A",
  # flake8-commas
  "COM",
  # flake8-comprehensions
  "C4",
  # flake8-datetimez
  "DTZ",
  # flake-debugger
  "T10",
  # flake8-django
  "DJ",
  # flake8-errmsg
  "EM",
  # flake8-executable
  "EXE",
  # lake8-implicit-str-concat
  "ISC",
  # lake8-import-conventions
  "ICN",
  # flake8-logging-format
  "G",
  # flake8-no-pep420
  "INP",
  # flake8-pie
  "PIE",
  # flake8-print
  "T20",
  # flake8-pyi
  "PYI",
  # flake8-pytest-style
  "PT",
  # flake8-quotes
  "Q",
  # flake8-raise
  "RSE",
  # flake8-return
  "RET",
  # flake8-self
  "SLF",
  # flake8-simplify
  "SIM",
  # flake8-tidy-imports
  "TID",
  # flake8-type-checking
  "TCH",
  # flake8-unused-arguments
  # "ARG",
  # flake8-use-pathlib
  "PTH",
  # eradicate
  "ERA",
  # pandas-vet
  "PD",
  # pygrep-hooks
  "PGH",
  # Pylint
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  # tryceratops
  "TRY",
  # NumPy-specific rules
  "NPY",
  # Ruff-specific rules
  "RUF",
]
# line-length = 88
ignore = ["E501"]
# G004: loggins-f-string
# ANN101: missing-type-self
# ANN002: missing-type-args
# ANN003: missing-type-kwargs
# TCH003: typing-only-standard-library-import
# S101: use-of-assert
extend-ignore = ["TCH003", "ANN002", "ANN003", "ANN101", "G004", "S101"]
target-version = "py310"
[tool.ruff.pydocstyle]
convention = "google"
[tool.ruff.per-file-ignores]
"moveitpy_simple/__init__.py" = ["D104"]
"moveitpy_simple/moveitpy/__init__.py" = ["D104"]
"setup.py" = ["D100"]
# INP001: implicit-namespace-package
# SLF001: private-member-access
# ANN201: missing-return-type-undocumented-public-function
# PLR2004: magic-value-comparison
"moveitpy_simple/moveit_configs_utils/test/test_moveit_resources_configs.py" = ["INP001", "SLF001", "ANN201", "PLR2004"]
"moveitpy_simple/moveit_configs_utils/moveit_configs_utils/__init__.py" = ["F401"]
"moveitpy_simple/moveit_configs_utils/test/test_file_loaders.py" = ["INP001", "ANN201", "PLR2004"]
"moveitpy_simple/moveitpy/test/test_moveitpy.py" = ["INP001", "ANN201", "PLR2004", "SLF001"]
"example/visualizer.py" = ["INP001"]
