# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Build and Test (humble)

# This determines when this workflow is run
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  industrial_ci:
    strategy:
      fail-fast: false

    env:
      ROS_DISTRO: humble
      ROS_REPO: main
      CI_NAME: build-and-test
      DOCKER_IMAGE: moveit/moveit2:humble-source
      UNDERLAY: /root/ws_moveit/install
      # UPSTREAM_WORKSPACE: moveitpy_simple.repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
